version: '3'
services:
  app: 
    restart: unless-stopped
    env_file:
      - .env
    build: ./
  nginx: 
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_NAME=$SERVER_NAME
    volumes:
      - nginx_cache:/var/cache/nginx
      - ./nginx/templates:/etc/nginx/templates
      - /etc/ssl:/etc/nginx/ssl:ro

volumes:
  nginx_cache:
    driver: local