version: '3'
services:
  app: 
    env_file:
      - .env
    build: ./
  nginx: 
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - nginx_cache:/var/cache/nginx
volumes:
  nginx_cache:
    driver: local